  # Header
menu:
  Home: /
  Archives: /archives
  VPN: https://mtgh.ccwu.cc
  CF: https://dash.cloudflare.com/966a97add771f4475d548e4af846f47c
  Domain: https://my.dnshe.com/index.php?m=domain_hub
  飞书版: https://my.feishu.cn/wiki/JKQIwTlRKiQTYbkC7dZcEA0bnpe?from=from_copylink
